//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Differencial.Service.Test.ServRefConsultaFinanceiro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServRefConsultaFinanceiro.IConsultaFinanceiro")]
    public interface IConsultaFinanceiro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaFinanceiro/ListarMovimento", ReplyAction="http://tempuri.org/IConsultaFinanceiro/ListarMovimentoResponse")]
        string ListarMovimento(int mes, int ano, int tipoMovimentoSintetico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaFinanceiro/ListarMovimento", ReplyAction="http://tempuri.org/IConsultaFinanceiro/ListarMovimentoResponse")]
        System.Threading.Tasks.Task<string> ListarMovimentoAsync(int mes, int ano, int tipoMovimentoSintetico);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultaFinanceiroChannel : Differencial.Service.Test.ServRefConsultaFinanceiro.IConsultaFinanceiro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaFinanceiroClient : System.ServiceModel.ClientBase<Differencial.Service.Test.ServRefConsultaFinanceiro.IConsultaFinanceiro>, Differencial.Service.Test.ServRefConsultaFinanceiro.IConsultaFinanceiro {
        
        public ConsultaFinanceiroClient() {
        }
        
        public ConsultaFinanceiroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaFinanceiroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaFinanceiroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaFinanceiroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ListarMovimento(int mes, int ano, int tipoMovimentoSintetico) {
            return base.Channel.ListarMovimento(mes, ano, tipoMovimentoSintetico);
        }
        
        public System.Threading.Tasks.Task<string> ListarMovimentoAsync(int mes, int ano, int tipoMovimentoSintetico) {
            return base.Channel.ListarMovimentoAsync(mes, ano, tipoMovimentoSintetico);
        }
    }
}
