//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Differencial.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Email() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Differencial.Domain.Resources.Email", typeof(Email).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html dir=&quot;ltr&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt; &lt;/title&gt;
        ///    &lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;div class=&quot; allowTextSelection&quot;&gt;
        ///        &lt;div&gt;
        ///            &lt;div class=&quot;&quot;&gt;
        ///                &lt;div&gt;
        ///                    &lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;
        ///                        &lt;table border=&quot;1&quot; width=&quot;780&quot;&gt;
        ///                            &lt;tbody&gt;
        ///                                &lt;tr&gt;
        ///                                    &lt;td&gt;PEDIDO Nº &lt;/td&gt;
        ///                                [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HtmlEmailCobrancaVistoria {
            get {
                return ResourceManager.GetString("HtmlEmailCobrancaVistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional //EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;&lt;head&gt;
        ///    &lt;!--[if gte mso 9]&gt;&lt;xml&gt;
        ///     &lt;o:OfficeDocumentSettings&gt;
        ///      &lt;o:AllowPNG/&gt;
        ///      &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///     &lt;/o:OfficeDocumentSettings&gt;
        ///    &lt;/xml&gt;&lt;![endif]--&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charse [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HtmlEmailOperadorGerarNovoAcesso {
            get {
                return ResourceManager.GetString("HtmlEmailOperadorGerarNovoAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional //EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;&lt;head&gt;
        ///    &lt;!--[if gte mso 9]&gt;&lt;xml&gt;
        ///     &lt;o:OfficeDocumentSettings&gt;
        ///      &lt;o:AllowPNG/&gt;
        ///      &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///     &lt;/o:OfficeDocumentSettings&gt;
        ///    &lt;/xml&gt;&lt;![endif]--&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charse [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HtmlEmailOperadorGerarPrimeiroAcesso {
            get {
                return ResourceManager.GetString("HtmlEmailOperadorGerarPrimeiroAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;div&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;
        ///&lt;font face=&quot;Arial&quot; size=&quot;2&quot; style=&quot;color:rgb(204,0,0)&quot;&gt;&lt;/font&gt;&lt;br&gt;
        ///&lt;br&gt;
        ///&lt;font size=&quot;4&quot; color=&quot;red&quot;&gt;&lt;b&gt;PRAZO MÁXIMO DE ENTREGA DO LAUDO: {prazoentrega}&lt;/b&gt;&lt;/font&gt;&lt;br&gt;
        ///&lt;br&gt;
        ///&lt;font size=&quot;3&quot;&gt;&lt;b&gt;Prezado Inspetor,&lt;br&gt;&lt;/font&gt;&lt;br&gt;
        ///&lt;/b&gt;&lt;font size=&quot;4&quot; color=&quot;red&quot;&gt;&lt;b&gt;{mensagem-movimento}&lt;/b&gt;&lt;/font&gt;&lt;br&gt;
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///&lt;/b&gt;&lt;font size=&quot;2&quot;&gt;&lt;b&gt;Favor providenciar inspeção conforme dados abaixo, retornando o relatório em até dois dias úteis.&lt;/b&gt;&lt;/font&gt;&lt;br&gt;
        ///&lt;br&gt;
        ///&lt;font size=&quot;2&quot;&gt;&lt;b&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HtmlEmailSolicitacaoVistoria {
            get {
                return ResourceManager.GetString("HtmlEmailSolicitacaoVistoria", resourceCulture);
            }
        }
    }
}
