//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Differencial.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensValidacaoServicos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensValidacaoServicos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Differencial.Domain.Resources.MensagensValidacaoServicos", typeof(MensagensValidacaoServicos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informada já está cadastrado para um operador do sistema..
        /// </summary>
        public static string OperadorRnEmailDuplicado {
            get {
                return ResourceManager.GetString("OperadorRnEmailDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse operador não está autorizado a acessar o sistema..
        /// </summary>
        public static string OperadorRnLogonAcessoSistema {
            get {
                return ResourceManager.GetString("OperadorRnLogonAcessoSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail de acesso inválido, verifique o e-mail digitado e tente novamente..
        /// </summary>
        public static string OperadorRnLogonInvalido {
            get {
                return ResourceManager.GetString("OperadorRnLogonInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O operador não realizou a ativação do acesso, para ativar verifique no seu e-mail ou realize alteração de senha no link &apos;Esqueceu a Senha&apos;..
        /// </summary>
        public static string OperadorRnLogonPrimeiroAcesso {
            get {
                return ResourceManager.GetString("OperadorRnLogonPrimeiroAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha de acesso inválida, tente novamente ou realize alteração de senha no link &apos;Esqueceu a Senha&apos;..
        /// </summary>
        public static string OperadorRnLogonSenhaInvalida {
            get {
                return ResourceManager.GetString("OperadorRnLogonSenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operador não encontrado para realizar a mudança de senha..
        /// </summary>
        public static string OperadorRnMudarSenha {
            get {
                return ResourceManager.GetString("OperadorRnMudarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi informado a quilometragem de deslocamento para realizar a vistoria, portanto não é possível processar os lançamentos financeiros..
        /// </summary>
        public static string RnDeslocamentoRealizado_NaoInformado {
            get {
                return ResourceManager.GetString("RnDeslocamentoRealizado_NaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possivél verificar no Google Maps a rota. Por favor contate o suporte técnico..
        /// </summary>
        public static string RnDistanciaRotaZeroResults {
            get {
                return ResourceManager.GetString("RnDistanciaRotaZeroResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O não foi possível determinar a geolocalização no Google Maps do endereço informado. Por favor valide os dados informados e tente novamente..
        /// </summary>
        public static string RnEnderecoBuscarGeoZeroResult {
            get {
                return ResourceManager.GetString("RnEnderecoBuscarGeoZeroResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há implementaçao para interpretar e-mail de solicitação da seguradora {0}. Contate o suporte técnico..
        /// </summary>
        public static string RnFactorySolicitacaoEmail_NaoImplementada {
            get {
                return ResourceManager.GetString("RnFactorySolicitacaoEmail_NaoImplementada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma seguradora cadastrada com remetente de novas solicitações para {0}..
        /// </summary>
        public static string RnFactorySolicitacaoEmail_RemetenteNaoEncontrado {
            get {
                return ResourceManager.GetString("RnFactorySolicitacaoEmail_RemetenteNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A seguradora {0} não tem habilitada configuração de {1}..
        /// </summary>
        public static string RnFactorySolicitacaoEmail_SeguradoraNaoSolicita {
            get {
                return ResourceManager.GetString("RnFactorySolicitacaoEmail_SeguradoraNaoSolicita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve uma falha na integração com Google Maps. {0}.
        /// </summary>
        public static string ServExGoogleApiGeoResul {
            get {
                return ResourceManager.GetString("ServExGoogleApiGeoResul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há e-mail cadastrado para que seja realizado o envio de e-mail..
        /// </summary>
        public static string SolicitacaoRegistrarComunicacaoNaoHaEmail {
            get {
                return ResourceManager.GetString("SolicitacaoRegistrarComunicacaoNaoHaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido o cadastro de registro duplicado, já existe solicitação para essa seguradora com mesmo Nº Cia..
        /// </summary>
        public static string SolicitacaoRnCadastroDuplicado {
            get {
                return ResourceManager.GetString("SolicitacaoRnCadastroDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há vistoriador definido para receber essa solicitação. Por favor defina através do botão &apos;Definir Vistoriador&apos;.
        /// </summary>
        public static string SolicitacaoRnEnviarParaVistoriador {
            get {
                return ResourceManager.GetString("SolicitacaoRnEnviarParaVistoriador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A solicitação ainda não tem valores de Pré-Acordo(R$) registrados pelo gerente. Esse dado deve ser devidamente registrado na aba Gestão - Vistoriador campos Pré-Acordo..
        /// </summary>
        public static string SolicitacaoRnInserirLancamentosCustoDeslocamentoAcordado {
            get {
                return ResourceManager.GetString("SolicitacaoRnInserirLancamentosCustoDeslocamentoAcordado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A solicitação ainda não tem Rota Realizados(Km/R$) pelo vistoriador. Esse dado deve ser preenchido na aba Inspeção - Rota - Informar Km Realizado.
        /// </summary>
        public static string SolicitacaoRnInserirLancamentosCustoDeslocamentoRealizado {
            get {
                return ResourceManager.GetString("SolicitacaoRnInserirLancamentosCustoDeslocamentoRealizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O produto da solicitação não tem valor de receita para o campo {0}. Esse dado deve ser devidamente registrado no cadastro de produtos..
        /// </summary>
        public static string SolicitacaoRnInserirLancamentosReceitaProduto {
            get {
                return ResourceManager.GetString("SolicitacaoRnInserirLancamentosReceitaProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O produto selecionado não possui dados financeiros/contrato cadastrados. O cadastro desse produto deve ser revisado..
        /// </summary>
        public static string SolicitacaoRnProdutoSemContrato {
            get {
                return ResourceManager.GetString("SolicitacaoRnProdutoSemContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A solicitação não possúi agendamento realizado. O agendamento deve ser preenchido na aba Inspeção - aba Agenda - botão Agendar. .
        /// </summary>
        public static string SolicitacaoRnValidarExiteAgendamento {
            get {
                return ResourceManager.GetString("SolicitacaoRnValidarExiteAgendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A solicitação não possui fotos da inspeção realizada e/ou a atividade não foi concluída.  
        ///As fotos devem ser enviadas na aba Inspeção - aba Anexar Fotos - painel Drop files. 
        ///A atividade dever ser concluída no botão Concluir..
        /// </summary>
        public static string SolicitacaoRnValidarExiteInspecaoRealizada {
            get {
                return ResourceManager.GetString("SolicitacaoRnValidarExiteInspecaoRealizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A solicitação não tem laudo concluído. O laudo deve ser anexado e a atividade concluída na aba Anallise - aba Laudo - campo Laudo Final..
        /// </summary>
        public static string SolicitacaoRnValidarExiteLaudoConcluido {
            get {
                return ResourceManager.GetString("SolicitacaoRnValidarExiteLaudoConcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir o solicitante pois já existe registros de solicitação no sistema..
        /// </summary>
        public static string SolicitanteRnExisteSolicitacoes {
            get {
                return ResourceManager.GetString("SolicitanteRnExisteSolicitacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O operador solicitante de seguradora não pode ter mais nenhum papel interno da Differencial..
        /// </summary>
        public static string SolicitanteRnOperadorExclusivo {
            get {
                return ResourceManager.GetString("SolicitanteRnOperadorExclusivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro ainda não possui valor. Você deve editar os valores dos produtos deste vistoriador poder ativar..
        /// </summary>
        public static string VistoriadorProdutoRnAtivarSemValor {
            get {
                return ResourceManager.GetString("VistoriadorProdutoRnAtivarSemValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro ainda não possui valor. Você deve editar os valores dos produtos deste vistoriador poder desativar..
        /// </summary>
        public static string VistoriadorProdutoRnDesativarSemValor {
            get {
                return ResourceManager.GetString("VistoriadorProdutoRnDesativarSemValor", resourceCulture);
            }
        }
    }
}
